#CONVERTER UMA STRING PARA UM SET APENAS APRESENTA OS CARACTERES 1 UNICA VEZ SEM REPETIÇÃO, DEPOIS SO VER QUAL É O TAMANHO DESSE SET "CHAVE"
s =  len(set(input()))

#SE FOR IMPAR (ODD)
if s % 2 == 1:
  print('IGNORE HIM!')
#PELO CONTRARIO SE FOR PAR
else:
  print('CHAT WITH HER!')
